# -*- coding: utf-8 -*-
"""data_loader.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a6UC6SqELcvGMr2QRf9n0mug02xp6SOd
"""

import pandas as pd

def load_ratings(path):
    return pd.read_csv(
        path,
        sep='\t',
        names=['user_id', 'movie_id', 'rating', 'timestamp'],
        usecols=['user_id', 'movie_id', 'rating']
    )

def load_movies(path):

    genre_cols = [
        "unknown", "Action", "Adventure", "Animation", "Children's", "Comedy", "Crime",
        "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror", "Musical", "Mystery",
        "Romance", "Sci-Fi", "Thriller", "War", "Western"
    ]

    col_names = ['movie_id', 'movie_title', 'release_date', 'video_release_date', 'IMDb_URL'] + genre_cols

    return pd.read_csv(
        path,
        sep='|',
        names=col_names,
        usecols=['movie_id', 'movie_title'] + genre_cols ,
        encoding='latin1'
    )

def load_users(path):

    return pd.read_csv(
        path,
        sep='|',
        names=['user_id', 'age', 'gender', 'occupation', 'zip_code'],
        usecols=['user_id']
    )